In [1]:
from MBDOE import *

[    0.00] Initializing mpi-sppy


In [2]:
mbdoe_obj = MBDOE('./emimtf2n/R32/Final_Results/MBDoE/r32_emimtf2n_subset.csv')


para_file = './emimtf2n/R32/Final_Results/MBDoE/Params/PR_params_3params_Opt1.csv'
design_var_set = [1,2,3]

# construct automatically from PRmodel
param_nam_dict = { 'fs.properties.PR_kappa_A["R32", "emimTf2N"]': 0, 
                    'fs.properties.PR_kappa_A["emimTf2N", "R32"]': 1,
                  'fs.properties.PR_kappa_B["R32","emimTf2N"]': 2}

total_fim = mbdoe_obj.sumDOE(para_file, design_var_set, param_nam_dict)

parameter set: {'fs.properties.PR_kappa_A["R32", "emimTf2N"]': 0.05611526243688785, 'fs.properties.PR_kappa_A["emimTf2N", "R32"]': -0.11697708014458684, 'fs.properties.PR_kappa_B["R32","emimTf2N"]': -0.09822244994811687}
2022-10-11 12:54:47 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available a

/media/psf/Home/dowlinglab/extractive-distillation2/modsel/paramest/MBDOE.py:156: RuntimeWarning: invalid value encountered in log10
  print('D-optimality:', np.log10(result.det))
/media/psf/Home/dowlinglab/extractive-distillation2/modsel/paramest/MBDOE.py:157: RuntimeWarning: invalid value encountered in log10
  print('E-optimality:', np.log10(result.min_eig))
/media/psf/Home/dowlinglab/extractive-distillation2/modsel/paramest/MBDOE.py:158: RuntimeWarning: invalid value encountered in log10
  print('Modified E-optimality:', np.log10(result.cond))


2022-10-11 12:54:48 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

2022-10-11 12:54:49 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

In [6]:
print(total_fim)
print(np.linalg.det(total_fim))
print(np.trace(total_fim))
print(np.linalg.eigvals(total_fim))

[[ 9.49802429e+10 -2.08799795e+10  1.57927533e+11]
 [-2.08799795e+10  5.04184099e+09 -3.47131667e+10]
 [ 1.57927533e+11 -3.47131667e+10  2.62592658e+11]]
1.718816242014893e+24
362614742020.98596
[3.62167831e+11 1.06196076e+04 4.46900774e+08]
