In [1]:
from MBDOE import *
from generalize_functions import PRModels

[    0.00] Initializing mpi-sppy


## Choose experiments and model

In [2]:
# Experiments 
data_file = './emimtf2n/R32/Final_Results/MBDoE/r32_emimtf2n_subset.csv'



# Decide on model 
para_file = './emimtf2n/R32/Final_Results/MBDoE/Params/PR_params_3params_Opt1.csv'
PR_type_opt = "3Params_Opt1"

model_creation = PRModels(para_file, configuration, 
                         comp_1= "R32", comp_2 = "emimTf2N", 
                         x_comp_1="x_R32", x_comp_2="x_emimTf2N", PR_type=PR_type_opt)

## Run pyomo.doe

In [3]:
data_exp = pd.read_csv(data_file)
print(len(data_exp))

27


In [4]:
mbdoe_obj = MBDOE(data_file, model_creation)

exp_set = range(len(data_exp))

total_fim = mbdoe_obj.sumDOE(exp_set, scale_opt=True)

parameter set: {'fs.properties.PR_kappa_A["R32", "emimTf2N"]': 0.05611526243688785, 'fs.properties.PR_kappa_A["emimTf2N", "R32"]': -0.11697708014458684, 'fs.properties.PR_kappa_B["R32", "emimTf2N"]': -0.09822244994811687}
==========Experiment index: 0 ===============
2022-10-12 00:10:28 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of 

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5688562393188477
Total wall clock time [s]: 0.5693731307983398
Existed information has been added.
The condition number is: 1.6168535367460483e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 3.04063760e+09 -1.14294856e+08  5.06656465e+09]
 [-1.14294856e+08  4.29624172e+06 -1.90447647e+08]
 [ 5.06656465e+09 -1.90447647e+08  8.44233373e+09]]
Trace: 11487267569.329437
Determinant: -3.6967207671977214e-06
Condition number: (-1540943451247543.5+1.0214899217850436e+16j)
Minimal eigen value: (-1.6586815856512257e-07-1.0995384170791215e-06j)
Eigen values: [ 1.14872676e+10+0.00000000e+00j -1.65868159e-07+1.09953842e-06j
 -1.65868159e-07-1.09953842e-06j]
Eigen vectors: [[ 0.51448647+0.j         -0.09138694+0.54107167j -0.09138694-0.54107167j]
 [-0.01933909+0.j          0.76697015+0.j          0.76697015-0.j        ]
 [ 0.857

/media/psf/Home/dowlinglab/extractive-distillation2/modsel/paramest/MBDOE.py:141: RuntimeWarning: invalid value encountered in log10
  print('D-optimality:', np.log10(result.det))


2022-10-12 00:10:29 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

/media/psf/Home/dowlinglab/extractive-distillation2/modsel/paramest/MBDOE.py:142: RuntimeWarning: invalid value encountered in log10
  print('E-optimality:', np.log10(result.min_eig))
/media/psf/Home/dowlinglab/extractive-distillation2/modsel/paramest/MBDOE.py:143: RuntimeWarning: invalid value encountered in log10
  print('Modified E-optimality:', np.log10(result.cond))


2022-10-12 00:10:30 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

2022-10-12 00:10:31 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

Failure initialization!
==========Experiment index: 5 ===============
2022-10-12 00:10:33 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAE

2022-10-12 00:10:34 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

2022-10-12 00:10:35 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

2022-10-12 00:10:36 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

2022-10-12 00:10:37 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    https://github.com/IDAES/Ipopt as part of the Institute for the Design of
    Advanced Energy Systems Process Systems Engineering Framework (IDAES PSE
    Framework) Copyright (c) 2018-2019. See https://github.com/I

Failure initialization!
==========Experiment index: 11 ===============
Failure initialization!
==========Experiment index: 12 ===============
Failure initialization!
==========Experiment index: 13 ===============
2022-10-12 00:10:40 [INFO] idaes.init.fs.state_block: Property package initialization: optimal - Optimal Solution Found.
All measurements are flattened.
Flatten measurement name: ['fs.state_block.pressure']
Sensitivity information is scaled by its corresponding parameter nominal value.
After practice: {'fs.state_block.pressure': [0]}
Ipopt 3.13.2: linear_solver=ma57
halt_on_ampl_error=yes
max_iter=3000


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt

This version of Ipopt was compiled from source code available at
    ht

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.4990198612213135
Total wall clock time [s]: 0.4995148181915283
Existed information has been added.
The condition number is: 6.229731463079622e+20 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 2.09839769e+09 -3.06600387e+07  3.99226278e+09]
 [-3.06600387e+07  4.47978942e+05 -5.83316177e+07]
 [ 3.99226278e+09 -5.83316177e+07  7.59539635e+09]]
Trace: 9694242013.494156
Determinant: 4.3401497347130376e-08
Condition number: (-8628872463211561+3.841564852190342e+16j)
Minimal eigen value: (-5.39603446021588e-08-2.4023088082423753e-07j)
Eigen values: [ 9.69424201e+09+0.00000000e+00j -5.39603446e-08+2.40230881e-07j
 -5.39603446e-08-2.40230881e-07j]
Eigen vectors: [[-0.46525063+0.j         -0.11063982+0.44242429j -0.11063982-0.44242429j]
 [ 0.00679785+0.j          0.85659322+0.j          0.85659322-0.j        ]
 [-0.88515289+0.

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5527925491333008
Total wall clock time [s]: 0.5535824298858643
Existed information has been added.
The condition number is: 4.144428501077251e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 1.26695515e+10 -4.83459654e+08  2.40793951e+10]
 [-4.83459654e+08  1.84484223e+07 -9.18849890e+08]
 [ 2.40793951e+10 -9.18849890e+08  4.57646246e+10]]
Trace: 58452624529.44656
Determinant: -0.00011658278263583967
Condition number: -2.7249336721466776e+16
Minimal eigen value: -2.1451026543115134e-06
Eigen values: [ 5.84526245e+10 -2.14510265e-06 -2.00104459e-07]
Eigen vectors: [[-0.46556317 -0.88417441 -0.63746352]
 [ 0.01776551 -0.05289306 -0.70026909]
 [-0.88483633  0.46415292  0.32134632]]
======Result summary======
Four design criteria log10() value:
A-optimality: 10.766804015806958
D-optimality: nan
E-optimality: nan
Modifie

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5249295234680176
Total wall clock time [s]: 0.5255622863769531
Existed information has been added.
The condition number is: 2.762385859346186e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 2.94377428e+10 -1.81407233e+09  5.59293610e+10]
 [-1.81407233e+09  1.11790447e+08 -3.44659260e+09]
 [ 5.59293610e+10 -3.44659260e+09  1.06261321e+11]]
Trace: 135810853729.82841
Determinant: -0.00028296360096747165
Condition number: (6544446458282467+3.1524937227230216e+16j)
Minimal eigen value: (8.573825499218563e-07-4.130056107618092e-06j)
Eigen values: [1.35810854e+11+0.00000000e+00j 8.57382550e-07+4.13005611e-06j
 8.57382550e-07-4.13005611e-06j]
Eigen vectors: [[ 0.46557003+0.j         -0.0922438 -0.55810003j -0.0922438 +0.55810003j]
 [-0.0286903 +0.j          0.7670299 +0.j          0.7670299 -0.j        ]
 [ 0.88454588+0.j 

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5161480903625488
Total wall clock time [s]: 0.5167155265808105
Existed information has been added.
The condition number is: 1.5037685270911377e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 5.25633685e+10 -4.60086581e+09  9.98467247e+10]
 [-4.60086581e+09  4.02713273e+08 -8.73957272e+09]
 [ 9.98467247e+10 -8.73957272e+09  1.89663804e+11]]
Trace: 242629885761.85992
Determinant: -0.018585491664999513
Condition number: -1.6725722457817664e+17
Minimal eigen value: -1.450639195848033e-06
Eigen values: [ 2.42629886e+11  1.01998256e-05 -1.45063920e-06]
Eigen vectors: [[ 0.46544616 -0.82473647 -0.26484474]
 [-0.04074045 -0.38248634  0.94675742]
 [ 0.88413805  0.41655006  0.18305093]]
======Result summary======
Four design criteria log10() value:
A-optimality: 11.38494429373615
D-optimality: nan
E-optimality: nan
Modified 

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5061140060424805
Total wall clock time [s]: 0.5067121982574463
Existed information has been added.
The condition number is: 6.819596570760151e+18 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 7.87464604e+10 -8.95081633e+09  1.49565157e+11]
 [-8.95081633e+09  1.01740589e+09 -1.70005133e+10]
 [ 1.49565157e+11 -1.70005133e+10  2.84072910e+11]]
Trace: 363836776542.7888
Determinant: -0.02630733473752615
Condition number: -3.925591400117787e+16
Minimal eigen value: -9.268330283479631e-06
Eigen values: [ 3.63836777e+11  2.08927890e-05 -9.26833028e-06]
Eigen vectors: [[ 0.46522412  0.29202758 -0.18437661]
 [-0.05288029  0.95149758  0.97053162]
 [ 0.88361202 -0.09681037  0.15515683]]
======Result summary======
Four design criteria log10() value:
A-optimality: 11.560906595338663
D-optimality: nan
E-optimality: nan
Modified E-o

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5061154365539551
Total wall clock time [s]: 0.5067405700683594
Existed information has been added.
The condition number is: 7.901226196777782e+20 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 1.53282263e+09 -1.39491258e+07  3.14170163e+09]
 [-1.39491258e+07  1.26941048e+05 -2.85903864e+07]
 [ 3.14170163e+09 -2.85903864e+07  6.43928981e+09]]
Trace: 7972239387.10921
Determinant: -1.0017614000912107e-08
Condition number: -5.576938887736996e+16
Minimal eigen value: -1.4295009408547022e-07
Eigen values: [ 7.97223939e+09  6.83160361e-07 -1.42950094e-07]
Eigen vectors: [[ 0.43848606  0.57955614 -0.15414751]
 [-0.00399035  0.76555242  0.98483779]
 [ 0.89872913 -0.27936389  0.07958058]]
======Result summary======
Four design criteria log10() value:
A-optimality: 9.901580331039446
D-optimality: nan
E-optimality: nan
Modified E

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.567223310470581
Total wall clock time [s]: 0.5677766799926758
Existed information has been added.
The condition number is: 4.4445635021771104e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 9.64114750e+09 -2.27391928e+08  1.97382207e+10]
 [-2.27391928e+08  5.36316752e+06 -4.65537124e+08]
 [ 1.97382207e+10 -4.65537124e+08  4.04098534e+10]]
Trace: 50056364113.03786
Determinant: -6.523639208040597e-05
Condition number: (-1870696021602394.5+3.165023525052922e+16j)
Minimal eigen value: (-9.315241180076594e-08-1.576042132768837e-06j)
Eigen values: [ 5.00563641e+10+0.00000000e+00j -9.31524118e-08+1.57604213e-06j
 -9.31524118e-08-1.57604213e-06j]
Eigen vectors: [[ 0.43886881+0.j         -0.02580538+0.53154937j -0.02580538-0.53154937j]
 [-0.01035097+0.j          0.80554313+0.j          0.80554313-0.j        ]
 [ 0.89849153+

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5627865791320801
Total wall clock time [s]: 0.5633790493011475
Existed information has been added.
The condition number is: 2.662044931436355e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 2.41483738e+10 -9.31271481e+08  4.94189564e+10]
 [-9.31271481e+08  3.59140776e+07 -1.90582045e+09]
 [ 4.94189564e+10 -1.90582045e+09  1.01134481e+11]]
Trace: 125318768650.93541
Determinant: -0.0005263462184948201
Condition number: (1.5126967284256026e+16+1.9390596711778804e+16j)
Minimal eigen value: (3.1343072687213183e-06-4.0177311867281586e-06j)
Eigen values: [1.25318769e+11+0.00000000e+00j 3.13430727e-06+4.01773119e-06j
 3.13430727e-06-4.01773119e-06j]
Eigen vectors: [[ 0.43897106+0.j          0.23666206+0.30990303j  0.23666206-0.30990303j]
 [-0.01692873+0.j          0.90293502+0.j          0.90293502-0.j        ]
 [ 0.898341

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.564453125
Total wall clock time [s]: 0.5653159618377686
Existed information has been added.
The condition number is: 2.5021855452762345e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 4.43193604e+10 -2.39183808e+09  9.06785530e+10]
 [-2.39183808e+09  1.29083303e+08 -4.89376233e+09]
 [ 9.06785530e+10 -4.89376233e+09  1.85530655e+11]]
Trace: 229979098883.19403
Determinant: -0.015011126130406822
Condition number: -2.1336970449208692e+16
Minimal eigen value: -1.0778432647251625e-05
Eigen values: [ 2.29979099e+11 -1.07784326e-05 -4.95924196e-06]
Eigen vectors: [[-0.43898791 -0.7535766   0.52266239]
 [ 0.02369141  0.53467803 -0.80638   ]
 [-0.89818057  0.38241563 -0.27672247]]
======Result summary======
Four design criteria log10() value:
A-optimality: 11.361688367964707
D-optimality: nan
E-optimality: nan
Modified E-opt

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 2.384185791015625e-07
Solve time with direct kaug mode [s]: 0.5589284896850586
Total wall clock time [s]: 0.5598485469818115
Existed information has been added.
The condition number is: 1.0889091175968378e+20 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 6.93252688e+10 -4.83226748e+09  1.41821424e+11]
 [-4.83226748e+09  3.36829692e+08 -9.88555927e+09]
 [ 1.41821424e+11 -9.88555927e+09  2.90129654e+11]]
Trace: 359791752655.9569
Determinant: 0.05783975676383107
Condition number: (-3049265305764330.5+4.9562145404525096e+16j)
Minimal eigen value: (-4.449440751475058e-07-7.232031567622142e-06j)
Eigen values: [ 3.59791753e+11+0.00000000e+00j -4.44944075e-07+7.23203157e-06j
 -4.44944075e-07-7.23203157e-06j]
Eigen vectors: [[ 0.43895518+0.j          0.03008688-0.24540032j  0.03008688+0.24540032j]
 [-0.03059705+0.j          0.96133142+0.j          0.96133142-0.j        ]
 [ 0.89798784+0

name: fs.state_block.pressure
Build time with direct kaug mode [s]: 4.76837158203125e-07
Solve time with direct kaug mode [s]: 0.5523836612701416
Total wall clock time [s]: 0.5534741878509521
Existed information has been added.
The condition number is: 1.1072521943878418e+19 ;
A condition number bigger than  1000000000000.0  is considered near singular.
FIM: [[ 9.82540133e+10 -8.41588785e+09  2.00982350e+11]
 [-8.41588785e+09  7.20857764e+08 -1.72150212e+10]
 [ 2.00982350e+11 -1.72150212e+10  4.11117101e+11]]
Trace: 510091972191.9909
Determinant: -0.11331661647804869
Condition number: -5.354845434588691e+16
Minimal eigen value: -9.525801975480763e-06
Eigen values: [ 5.10091972e+11  4.43854379e-05 -9.52580198e-06]
Eigen vectors: [[-0.43888517  0.7125488  -0.14520123]
 [ 0.03759244  0.62324324  0.98302572]
 [-0.89775644 -0.32224538  0.11214735]]
======Result summary======
Four design criteria log10() value:
A-optimality: 11.707648488674973
D-optimality: nan
E-optimality: nan
Modified E-o

In [5]:
print(total_fim)
print(np.linalg.det(total_fim))
print(np.trace(total_fim))
print(np.linalg.eigvals(total_fim))

[[ 6.76486223e+11 -1.00621591e+11  1.27065009e+12]
 [-1.00621591e+11  3.13878627e+10 -1.78804528e+11]
 [ 1.27065009e+12 -1.78804528e+11  2.40222247e+12]]
1.0243351769705212e+32
3110096553399.246
[3.08904672e+12 1.71505687e+09 1.93347733e+10]
