# Analyze FIM Results

System: R32/emimTF2N

In [1]:
import json
import sys
sys.path.append('../../../../')

import numpy as np

## PR 1param, Opt1

In [3]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_1param_Opt1.json')
  
data_PR_1param_Opt1 = json.load(f)

for i in data_PR_1param_Opt1:
    data_PR_1param_Opt1 = i
    
FIM_PR_1param_Opt1 = data_PR_1param_Opt1['Total']

FIM_PR_1param_Opt1_sc = np.zeros((1,1))

for i in range(1):
    for j in range(1):
        FIM_PR_1param_Opt1_sc[i,j] = FIM_PR_1param_Opt1[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_1param_Opt1_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_1param_Opt1_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_1param_Opt1_sc)
print('Determinant:',det)

Eigenvalues: [10470.00464292]

Eigenvectors: [[1.]]

Trace: 10470.004642920812

Determinant: 10470.004642920807


## PR 1param, Opt2

In [4]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_1param_Opt2.json')
  
data_PR_1param_Opt2 = json.load(f)

for i in data_PR_1param_Opt2:
    data_PR_1param_Opt2 = i
    
FIM_PR_1param_Opt2 = data_PR_1param_Opt2['Total']

FIM_PR_1param_Opt2_sc = np.zeros((1,1))

for i in range(1):
    for j in range(1):
        FIM_PR_1param_Opt2_sc[i,j] = FIM_PR_1param_Opt2[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_1param_Opt2_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_1param_Opt2_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_1param_Opt2_sc)
print('Determinant:',det)

Eigenvalues: [11.19851669]

Eigenvectors: [[1.]]

Trace: 11.198516687332532

Determinant: 11.198516687332532


## PR noTdep

In [5]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_noTdep.json')
  
data_PR_noTdep = json.load(f)

for i in data_PR_noTdep:
    data_PR_noTdep = i
    
FIM_PR_noTdep = data_PR_noTdep['Total']

FIM_PR_noTdep_sc = np.zeros((2,2))

for i in range(2):
    for j in range(2):
        FIM_PR_noTdep_sc[i,j] = FIM_PR_noTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_noTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_PR_noTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_noTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [  42427.48746709 1172076.85205063]

Eigenvectors: [[-0.97455025 -0.22416916]
 [ 0.22416916 -0.97455025]]

Cov Eigenvalues: [2.35696257e-05 8.53186374e-07]

Trace: 1214504.339517717

Determinant: 49728275950.84661
CN: 27.625412722347093


## PR 3params, Opt1

In [6]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_3param_Opt1.json')
  
data_PR_3params_Opt1 = json.load(f)

for i in data_PR_3params_Opt1:
    data_PR_3params_Opt1 = i
    
FIM_PR_3params_Opt1 = data_PR_3params_Opt1['Total']

FIM_PR_3params_Opt1_sc = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        FIM_PR_3params_Opt1_sc[i,j] = FIM_PR_3params_Opt1[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_3params_Opt1_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_PR_3params_Opt1_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_3params_Opt1_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [6.24558892e+02 2.17131971e-01 3.29745023e+00]

Eigenvectors: [[-0.47014575  0.84236831 -0.26339818]
 [ 0.08612441  0.34080075  0.93618237]
 [-0.87837666 -0.41745715  0.2327745 ]]

Cov Eigenvalues: [1.60113003e-03 4.60549404e+00 3.03264623e-01]

Trace: 628.0734738596357

Determinant: 447.17284248611367
CN: 2876.4022529446256


## PR 3params, Opt2

In [7]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_3param_Opt2.json')
  
data_PR_3params_Opt2 = json.load(f)

for i in data_PR_3params_Opt2:
    data_PR_3params_Opt2 = i
    
FIM_PR_3params_Opt2 = data_PR_3params_Opt2['Total']

FIM_PR_3params_Opt2_sc = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        FIM_PR_3params_Opt2_sc[i,j] = FIM_PR_3params_Opt2[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_3params_Opt2_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_PR_3params_Opt2_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_3params_Opt2_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.06342637e+04 1.49559029e+02 1.23731750e+01]

Eigenvectors: [[-0.07319592  0.9122032  -0.40314721]
 [ 0.02671372 -0.40229322 -0.91512105]
 [ 0.99695975  0.07775269 -0.00507788]]

Cov Eigenvalues: [4.84630814e-05 6.68632316e-03 8.08199997e-02]

Trace: 20796.195861654443

Determinant: 38184118.40286437
CN: 1667.6611821176848


## PR linTdep

In [8]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_linTdep.json')
  
data_PR_linTdep = json.load(f)

for i in data_PR_linTdep:
    data_PR_linTdep = i
    
FIM_PR_linTdep = data_PR_linTdep['Total']

FIM_PR_linTdep_sc = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        FIM_PR_linTdep_sc[i,j] = FIM_PR_linTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_linTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_PR_linTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_linTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.42521458e+03 2.65922061e+02 7.77310021e-01 1.64276372e-01]

Eigenvectors: [[ 0.39510657 -0.32132388 -0.78412275 -0.35467348]
 [-0.44588908 -0.51000672  0.29007191 -0.6759692 ]
 [ 0.61114986 -0.60647464  0.44539781  0.24557108]
 [-0.52112338 -0.51849072 -0.3203601   0.59746733]]

Cov Eigenvalues: [4.12334648e-04 3.76050034e-03 1.28648798e+00 6.08730269e+00]

Trace: 2692.0782264467425

Determinant: 82351.95376080667
CN: 14763.015243927133


## PR quadTdep

In [10]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_quadTdep.json')
  
data_PR_quadTdep = json.load(f)

for i in data_PR_quadTdep:
    data_PR_quadTdep = i
    
FIM_PR_quadTdep = data_PR_quadTdep['Total']

FIM_PR_quadTdep_sc = np.zeros((6,6))

for i in range(6):
    for j in range(6):
        FIM_PR_quadTdep_sc[i,j] = FIM_PR_quadTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_quadTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
# Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_PR_quadTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_quadTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.23371386e+04 2.60343538e+02 1.32287740e+01 2.12677456e-01
 8.54650300e-03 8.22396039e-05]

Eigenvectors: [[ 0.45104367  0.15268398  0.73712377 -0.04012275  0.4766875   0.03247998]
 [-0.10437935 -0.74644066  0.17244104  0.56160495  0.0995749   0.27727261]
 [ 0.82902366 -0.1647875  -0.13862732  0.08606271 -0.50748669 -0.03738705]
 [-0.07748034 -0.5045409   0.17615655 -0.36092246 -0.01606349 -0.7601849 ]
 [ 0.29954641 -0.21631945 -0.59420051 -0.19777335  0.6843154   0.0547881 ]
 [-0.05150806 -0.30166769  0.15358945 -0.7114801  -0.19174339  0.58291023]]

Cov Eigenvalues: [4.47684915e-05 3.84107862e-03 7.55927951e-02 4.70195580e+00
 1.17006921e+02 1.21595916e+04]

Trace: 22610.932206281006

Determinant: 11.49965617129065
CN: 271610483.6527655


## PR polyTdep

In [11]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_polyTdep.json')
  
data_PR_polyTdep = json.load(f)

for i in data_PR_polyTdep:
    data_PR_polyTdep = i
    
FIM_PR_polyTdep = data_PR_polyTdep['Total']

FIM_PR_polyTdep_sc = np.zeros((8,8))

for i in range(8):
    for j in range(8):
        FIM_PR_polyTdep_sc[i,j] = FIM_PR_polyTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_PR_polyTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_PR_polyTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_polyTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [3.05992363e+13 1.92446310e+07 1.78191387e+06 1.29537925e+05
 9.73617836e+03 1.10814649e+02 8.93060197e-02 4.34487792e+01]

Eigenvectors: [[ 2.96791437e-03  1.74768867e-01  4.72296299e-02  4.99418917e-01
   4.80280816e-02 -5.25612998e-01  4.05264846e-01  5.24377331e-01]
 [-3.40639147e-04 -3.92709921e-02 -1.46718794e-02 -3.35080989e-02
   7.34048908e-01 -3.99111695e-01  1.39462352e-01 -5.28734244e-01]
 [ 9.26364835e-03  6.23452857e-01  1.61027087e-02  5.79598483e-01
   6.30225078e-02  1.96629432e-01 -4.10528274e-01 -2.52696260e-01]
 [-8.55151730e-04 -4.50861117e-02 -5.37580273e-01 -2.71409147e-02
   5.58703627e-01  3.09264260e-01 -2.06536213e-01  5.07733893e-01]
 [ 9.56984879e-03  7.31111325e-01 -9.78691965e-03 -5.17121108e-01
   5.12126029e-02  1.34820277e-01  4.16786234e-01  5.79950774e-02]
 [-7.01952688e-04 -1.32061656e-02 -8.10386385e-01  1.62101511e-01
  -3.32149901e-01 -4.70646143e-02  3.07420925e-01 -3.31329616e-01]
 [ 7.02143905e-01  1.37072786e-01 -1.62401844e-01 -

## SRK 1param, Opt1

In [12]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_1param_Opt1.json')
  
data_SRK_1param_Opt1 = json.load(f)

for i in data_SRK_1param_Opt1:
    data_SRK_1param_Opt1 = i
    
FIM_SRK_1param_Opt1 = data_SRK_1param_Opt1['Total']

FIM_SRK_1param_Opt1_sc = np.zeros((1,1))

for i in range(1):
    for j in range(1):
        FIM_SRK_1param_Opt1_sc[i,j] = FIM_SRK_1param_Opt1[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_1param_Opt1_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_1param_Opt1_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_1param_Opt1_sc)
print('Determinant:',det)

Eigenvalues: [371388.07063497]

Eigenvectors: [[1.]]

Trace: 371388.07063497056

Determinant: 371388.07063497056


## SRK 1param, Opt2

In [13]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_1param_Opt2.json')
  
data_SRK_1param_Opt2 = json.load(f)

for i in data_SRK_1param_Opt2:
    data_SRK_1param_Opt2 = i
    
FIM_SRK_1param_Opt2 = data_SRK_1param_Opt2['Total']

FIM_SRK_1param_Opt2_sc = np.zeros((1,1))

for i in range(1):
    for j in range(1):
        FIM_SRK_1param_Opt2_sc[i,j] = FIM_SRK_1param_Opt2[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_1param_Opt2_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_1param_Opt2_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_1param_Opt2_sc)
print('Determinant:',det)

Eigenvalues: [18.62347963]

Eigenvectors: [[1.]]

Trace: 18.623479628152154

Determinant: 18.62347962815215


## SRK noTdep

In [14]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_noTdep.json')
  
data_SRK_noTdep = json.load(f)

for i in data_SRK_noTdep:
    data_SRK_noTdep = i
    
FIM_SRK_noTdep = data_SRK_noTdep['Total']

FIM_SRK_noTdep_sc = np.zeros((2,2))

for i in range(2):
    for j in range(2):
        FIM_SRK_noTdep_sc[i,j] = FIM_SRK_noTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_noTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_SRK_noTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_noTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [ 31256.19534044 281900.92878926]

Eigenvectors: [[-0.97686144 -0.21387318]
 [ 0.21387318 -0.97686144]]

Cov Eigenvalues: [3.19936572e-05 3.54734553e-06]

Trace: 313157.12412970007

Determinant: 8811150496.887798
CN: 9.019041688178932


## SRK 3params, Opt1

In [15]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_3params_Opt1.json')
  
data_SRK_3params_Opt1 = json.load(f)

for i in data_SRK_3params_Opt1:
    data_SRK_3params_Opt1 = i
    
FIM_SRK_3params_Opt1 = data_SRK_3params_Opt1['Total']

FIM_SRK_3params_Opt1_sc = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        FIM_SRK_3params_Opt1_sc[i,j] = FIM_SRK_3params_Opt1[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_3params_Opt1_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_SRK_3params_Opt1_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_3params_Opt1_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [8.45109789e+02 2.92704416e-01 3.19060521e+00]

Eigenvectors: [[-0.48891918  0.80203114 -0.34308028]
 [ 0.07035842  0.42826724  0.90090891]
 [-0.86948705 -0.41633306  0.26581772]]

Cov Eigenvalues: [1.18327821e-03 3.41641583e+00 3.13420161e-01]

Trace: 848.5930983650965

Determinant: 789.251610315053
CN: 2887.2464610163265


## SRK 3params, Opt2

In [16]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_3params_Opt2.json')
  
data_SRK_3params_Opt2 = json.load(f)

for i in data_SRK_3params_Opt2:
    data_SRK_3params_Opt2 = i
    
FIM_SRK_3params_Opt2 = data_SRK_3params_Opt2['Total']

FIM_SRK_3params_Opt2_sc = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        FIM_SRK_3params_Opt2_sc[i,j] = FIM_SRK_3params_Opt2[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_3params_Opt2_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_SRK_3params_Opt2_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_3params_Opt2_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [20016.20176651   204.78724068    20.22919569]

Eigenvectors: [[-0.09096951  0.81897215 -0.5665767 ]
 [ 0.03181476 -0.56625526 -0.82361569]
 [ 0.99534535  0.09294941 -0.02545656]]

Cov Eigenvalues: [4.99595284e-05 4.88311672e-03 4.94335027e-02]

Trace: 20241.218202879027

Determinant: 82920742.09450088
CN: 989.4709641668885


## SRK linTdep

In [17]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_linTdep.json')
  
data_SRK_linTdep = json.load(f)

for i in data_SRK_linTdep:
    data_SRK_linTdep = i
    
FIM_SRK_linTdep = data_SRK_linTdep['Total']

FIM_SRK_linTdep_sc = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        FIM_SRK_linTdep_sc[i,j] = FIM_SRK_linTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_linTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_SRK_linTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_linTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.79255474e+03 3.00189406e+02 9.55375840e-01 1.76097066e-01]

Eigenvectors: [[ 0.41889839 -0.30150889 -0.79776363 -0.31175266]
 [-0.42162533 -0.53353564  0.24965259 -0.68938044]
 [ 0.63807981 -0.57247448  0.46497351  0.22119394]
 [-0.48950013 -0.54470641 -0.29162718  0.61533579]]

Cov Eigenvalues: [3.58095040e-04 3.33123015e-03 1.04670849e+00 5.67868631e+00]

Trace: 3093.8756153169415

Determinant: 141033.8723970868
CN: 15858.04236661735


## SRK quadTdep

In [18]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_quadTdep.json')
  
data_SRK_quadTdep = json.load(f)

for i in data_SRK_quadTdep:
    data_SRK_quadTdep = i
    
FIM_SRK_quadTdep = data_SRK_quadTdep['Total']

FIM_SRK_quadTdep_sc = np.zeros((6,6))

for i in range(6):
    for j in range(6):
        FIM_SRK_quadTdep_sc[i,j] = FIM_SRK_quadTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_quadTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_SRK_quadTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_quadTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.50022600e+04 1.83107856e+02 1.45976310e+01 2.82823158e-01
 9.67159810e-03 1.43736011e-05]

Eigenvectors: [[ 0.45713706  0.22963461  0.71802539 -0.02030101  0.4713395   0.01265431]
 [-0.07731419 -0.70307161  0.20991027  0.64723394  0.12164681  0.1481242 ]
 [ 0.83174476 -0.15876469 -0.1437368   0.07214069 -0.5068664  -0.01470837]
 [-0.02386753 -0.19776754  0.07825928 -0.0244337   0.02543783 -0.97619145]
 [ 0.29473038 -0.2556613  -0.56922202 -0.19391122  0.69690272  0.02196882]
 [-0.07624454 -0.56857482  0.29929704 -0.73298925 -0.14073769  0.15572536]]

Cov Eigenvalues: [3.99963844e-05 5.46126214e-03 6.85042663e-02 3.53577835e+00
 1.03395529e+02 6.95719876e+04]

Trace: 25200.25797660742

Determinant: 2.627528423736401
CN: 1739456921.9709058


## SRK polyTdep

In [19]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_polyTdep.json')
  
data_SRK_polyTdep = json.load(f)

for i in data_SRK_polyTdep:
    data_SRK_polyTdep = i
    
FIM_SRK_polyTdep = data_SRK_polyTdep['Total']

FIM_SRK_polyTdep_sc = np.zeros((8,8))

for i in range(8):
    for j in range(8):
        FIM_SRK_polyTdep_sc[i,j] = FIM_SRK_polyTdep[i][j]*1E-10

eigvals, eigvecs = np.linalg.eig(FIM_SRK_polyTdep_sc)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
#Eigvals of covariance
eig_cov = 1/eigvals
print('Cov Eigenvalues:',eig_cov)
print('')
trace = np.trace(FIM_SRK_polyTdep_sc)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_polyTdep_sc)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [6.16761010e+06 4.33621956e+04 4.76429466e+03 3.28907184e+01
 3.96053052e+00 2.81086577e-02 1.43195806e-03 3.52239531e-06]

Eigenvectors: [[ 0.23936248 -0.2415815   0.46054146  0.2707524  -0.62235571  0.08471086
   0.45076036 -0.03537283]
 [-0.03351188  0.32975732  0.15992713 -0.57159844 -0.23347979 -0.61116713
   0.14352154 -0.29866218]
 [ 0.68330892 -0.1708741   0.43998533 -0.13325675  0.23814515 -0.11025572
  -0.47139799  0.03822322]
 [-0.07384326  0.66180691  0.36558324 -0.18075418 -0.11801478  0.45266065
  -0.08729223  0.40470548]
 [ 0.6494141   0.3175355  -0.42405654 -0.04897003  0.17096396  0.14154628
   0.49419518 -0.04144417]
 [-0.05393061  0.43485796  0.28033609  0.58547589  0.27282879 -0.07750642
  -0.02850192 -0.552598  ]
 [ 0.21058282  0.25341146 -0.41205417  0.29568476 -0.58709364 -0.17540669
  -0.50679191  0.04398758]
 [-0.01504458  0.10753853  0.08298061  0.34194936  0.19793129 -0.58773354
   0.21095353  0.65976136]]

Cov Eigenvalues: [1.62137357e-07 2.3061