# Analyze FIM Results

System: R32/emimTF2N

In [1]:
import json
import sys
sys.path.append('../../../../')

import numpy as np

## PR 1param, Opt1

In [2]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_1param_Opt1.json')
  
data_PR_1param_Opt1 = json.load(f)

for i in data_PR_1param_Opt1:
    data_PR_1param_Opt1 = i
    
FIM_PR_1param_Opt1 = data_PR_1param_Opt1['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_1param_Opt1)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_1param_Opt1)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_1param_Opt1)
print('Determinant:',det)

Eigenvalues: [1.04700046e+14]

Eigenvectors: [[1.]]

Trace: 104700046429208.12

Determinant: 104700046429207.92


## PR 1param, Opt2

In [3]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_1param_Opt2.json')
  
data_PR_1param_Opt2 = json.load(f)

for i in data_PR_1param_Opt2:
    data_PR_1param_Opt2 = i
    
FIM_PR_1param_Opt2 = data_PR_1param_Opt2['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_1param_Opt2)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_1param_Opt2)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_1param_Opt2)
print('Determinant:',det)

Eigenvalues: [1.11985167e+11]

Eigenvectors: [[1.]]

Trace: 111985166873.32532

Determinant: 111985166873.32521


## PR noTdep

In [4]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_noTdep.json')
  
data_PR_noTdep = json.load(f)

for i in data_PR_noTdep:
    data_PR_noTdep = i
    
FIM_PR_noTdep = data_PR_noTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_noTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_noTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_noTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [4.24274875e+14 1.17207685e+16]

Eigenvectors: [[-0.97455025 -0.22416916]
 [ 0.22416916 -0.97455025]]

Trace: 1.214504339517717e+16

Determinant: 4.9728275950846656e+30
CN: 27.62541272234709


## PR 3params, Opt1

In [5]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_3param_Opt1.json')
  
data_PR_3params_Opt1 = json.load(f)

for i in data_PR_3params_Opt1:
    data_PR_3params_Opt1 = i
    
FIM_PR_3params_Opt1 = data_PR_3params_Opt1['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_3params_Opt1)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_3params_Opt1)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_3params_Opt1)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [6.24558892e+12 2.17131971e+09 3.29745023e+10]

Eigenvectors: [[-0.47014575  0.84236831 -0.26339818]
 [ 0.08612441  0.34080075  0.93618237]
 [-0.87837666 -0.41745715  0.2327745 ]]

Trace: 6280734738596.357

Determinant: 4.471728424860832e+32
CN: 2876.4022529449912


## PR 3params, Opt2

In [6]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_3param_Opt2.json')
  
data_PR_3params_Opt2 = json.load(f)

for i in data_PR_3params_Opt2:
    data_PR_3params_Opt2 = i
    
FIM_PR_3params_Opt2 = data_PR_3params_Opt2['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_3params_Opt2)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_3params_Opt2)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_3params_Opt2)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.06342637e+14 1.49559029e+12 1.23731750e+11]

Eigenvectors: [[-0.07319592  0.9122032  -0.40314721]
 [ 0.02671372 -0.40229322 -0.91512105]
 [ 0.99695975  0.07775269 -0.00507788]]

Trace: 207961958616544.44

Determinant: 3.818411840286428e+37
CN: 1667.6611821176853


## PR linTdep

In [7]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_linTdep.json')
  
data_PR_linTdep = json.load(f)

for i in data_PR_linTdep:
    data_PR_linTdep = i
    
FIM_PR_linTdep = data_PR_linTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_linTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_linTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_linTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.42521458e+13 2.65922061e+12 7.77310021e+09 1.64276372e+09]

Eigenvectors: [[ 0.39510657 -0.32132388 -0.78412275 -0.35467348]
 [-0.44588908 -0.51000672  0.29007191 -0.6759692 ]
 [ 0.61114986 -0.60647464  0.44539781  0.24557108]
 [-0.52112338 -0.51849072 -0.3203601   0.59746733]]

Trace: 26920782264467.426

Determinant: 8.235195376080783e+44
CN: 14763.01524392535


## PR quadTdep

In [8]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_quadTdep.json')
  
data_PR_quadTdep = json.load(f)

for i in data_PR_quadTdep:
    data_PR_quadTdep = i
    
FIM_PR_quadTdep = data_PR_quadTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_quadTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_quadTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_quadTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.23371386e+14 2.60343538e+12 1.32287740e+11 2.12677456e+09
 8.54650301e+07 8.22396040e+05]

Eigenvectors: [[ 0.45104367  0.15268398  0.73712377 -0.04012275  0.4766875   0.03247998]
 [-0.10437935 -0.74644066  0.17244104  0.56160495  0.0995749   0.27727261]
 [ 0.82902366 -0.1647875  -0.13862732  0.08606271 -0.50748669 -0.03738705]
 [-0.07748034 -0.5045409   0.17615655 -0.36092246 -0.01606349 -0.7601849 ]
 [ 0.29954641 -0.21631945 -0.59420051 -0.19777335  0.6843154   0.0547881 ]
 [-0.05150806 -0.30166769  0.15358945 -0.7114801  -0.19174339  0.58291023]]

Trace: 226109322062810.06

Determinant: 1.1499656169507561e+61
CN: 271610483.2603539


## PR polyTdep

In [9]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/PR_polyTdep.json')
  
data_PR_polyTdep = json.load(f)

for i in data_PR_polyTdep:
    data_PR_polyTdep = i
    
FIM_PR_polyTdep = data_PR_polyTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_PR_polyTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_PR_polyTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_PR_polyTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [3.05992363e+23 1.92446310e+17 1.78191387e+16 1.29537925e+15
 9.73617811e+13 1.10814648e+12 8.88089455e+08 4.34486794e+11]

Eigenvectors: [[ 2.96791437e-03  1.74768867e-01 -4.72296299e-02  4.99418917e-01
  -4.80281075e-02  5.25613076e-01  4.05261155e-01  5.24387758e-01]
 [-3.40639147e-04 -3.92709921e-02  1.46718794e-02 -3.35080990e-02
  -7.34048926e-01  3.99111642e-01  1.39461521e-01 -5.28728573e-01]
 [ 9.26364835e-03  6.23452857e-01 -1.61027087e-02  5.79598483e-01
  -6.30225222e-02 -1.96629479e-01 -4.10526771e-01 -2.52703605e-01]
 [-8.55151730e-04 -4.50861117e-02  5.37580273e-01 -2.71409150e-02
  -5.58703622e-01 -3.09264212e-01 -2.06535759e-01  5.07728172e-01]
 [ 9.56984879e-03  7.31111325e-01  9.78691967e-03 -5.17121109e-01
  -5.12125537e-02 -1.34820251e-01  4.16786774e-01  5.79993223e-02]
 [-7.01952688e-04 -1.32061656e-02  8.10386385e-01  1.62101511e-01
   3.32149927e-01  4.70645905e-02  3.07421390e-01 -3.31325074e-01]
 [ 7.02143905e-01  1.37072786e-01  1.62401844e-01 -

## SRK 1param, Opt1

In [10]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_1param_Opt1.json')
  
data_SRK_1param_Opt1 = json.load(f)

for i in data_SRK_1param_Opt1:
    data_SRK_1param_Opt1 = i
    
FIM_SRK_1param_Opt1 = data_SRK_1param_Opt1['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_1param_Opt1)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_1param_Opt1)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_1param_Opt1)
print('Determinant:',det)

Eigenvalues: [3.71388071e+15]

Eigenvectors: [[1.]]

Trace: 3713880706349705.5

Determinant: 3713880706349700.5


## SRK 1param, Opt2

In [11]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_1param_Opt2.json')
  
data_SRK_1param_Opt2 = json.load(f)

for i in data_SRK_1param_Opt2:
    data_SRK_1param_Opt2 = i
    
FIM_SRK_1param_Opt2 = data_SRK_1param_Opt2['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_1param_Opt2)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_1param_Opt2)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_1param_Opt2)
print('Determinant:',det)

Eigenvalues: [1.86234796e+11]

Eigenvectors: [[1.]]

Trace: 186234796281.52155

Determinant: 186234796281.52158


## SRK noTdep

In [12]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_noTdep.json')
  
data_SRK_noTdep = json.load(f)

for i in data_SRK_noTdep:
    data_SRK_noTdep = i
    
FIM_SRK_noTdep = data_SRK_noTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_noTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_noTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_noTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [3.12561953e+14 2.81900929e+15]

Eigenvectors: [[-0.97686144 -0.21387318]
 [ 0.21387318 -0.97686144]]

Trace: 3131571241297000.5

Determinant: 8.811150496887805e+29
CN: 9.019041688178921


## SRK 3params, Opt1

In [13]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_3params_Opt1.json')
  
data_SRK_3params_Opt1 = json.load(f)

for i in data_SRK_3params_Opt1:
    data_SRK_3params_Opt1 = i
    
FIM_SRK_3params_Opt1 = data_SRK_3params_Opt1['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_3params_Opt1)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_3params_Opt1)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_3params_Opt1)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [8.45109789e+12 2.92704416e+09 3.19060521e+10]

Eigenvectors: [[-0.48891918  0.80203114 -0.34308028]
 [ 0.07035842  0.42826724  0.90090891]
 [-0.86948705 -0.41633306  0.26581772]]

Trace: 8485930983650.965

Determinant: 7.892516103150987e+32
CN: 2887.2464610169272


## SRK 3params, Opt2

In [14]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_3params_Opt2.json')
  
data_SRK_3params_Opt2 = json.load(f)

for i in data_SRK_3params_Opt2:
    data_SRK_3params_Opt2 = i
    
FIM_SRK_3params_Opt2 = data_SRK_3params_Opt2['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_3params_Opt2)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_3params_Opt2)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_3params_Opt2)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.00162018e+14 2.04787241e+12 2.02291957e+11]

Eigenvectors: [[-0.09096951  0.81897215 -0.5665767 ]
 [ 0.03181476 -0.56625526 -0.82361569]
 [ 0.99534535  0.09294941 -0.02545656]]

Trace: 202412182028790.25

Determinant: 8.292074209450069e+37
CN: 989.4709641668719


## SRK linTdep

In [15]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_linTdep.json')
  
data_SRK_linTdep = json.load(f)

for i in data_SRK_linTdep:
    data_SRK_linTdep = i
    
FIM_SRK_linTdep = data_SRK_linTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_linTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_linTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_linTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.79255474e+13 3.00189406e+12 9.55375840e+09 1.76097066e+09]

Eigenvectors: [[ 0.41889839 -0.30150889 -0.79776363 -0.31175266]
 [-0.42162533 -0.53353564  0.24965259 -0.68938044]
 [ 0.63807981 -0.57247448  0.46497351  0.22119394]
 [-0.48950013 -0.54470641 -0.29162718  0.61533579]]

Trace: 30938756153169.414

Determinant: 1.4103387239710356e+45
CN: 15858.042366620974


## SRK quadTdep

In [16]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_quadTdep.json')
  
data_SRK_quadTdep = json.load(f)

for i in data_SRK_quadTdep:
    data_SRK_quadTdep = i
    
FIM_SRK_quadTdep = data_SRK_quadTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_quadTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_quadTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_quadTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [2.50022600e+14 1.83107856e+12 1.45976310e+11 2.82823158e+09
 9.67159810e+07 1.43736011e+05]

Eigenvectors: [[ 0.45713706  0.22963461  0.71802539 -0.02030101  0.4713395   0.01265431]
 [-0.07731419 -0.70307161  0.20991027  0.64723394  0.12164681  0.1481242 ]
 [ 0.83174476 -0.15876469 -0.1437368   0.07214069 -0.5068664  -0.01470837]
 [-0.02386753 -0.19776754  0.07825928 -0.0244337   0.02543783 -0.97619145]
 [ 0.29473038 -0.2556613  -0.56922202 -0.19391122  0.69690272  0.02196882]
 [-0.07624454 -0.56857482  0.29929704 -0.73298925 -0.14073769  0.15572536]]

Trace: 252002579766074.16

Determinant: 2.6275284242997703e+60
CN: 1739456921.204277


## SRK polyTdep

In [17]:
# Opening JSON file
f = open('../../../../emimtf2n_FIM_info/SRK_polyTdep.json')
  
data_SRK_polyTdep = json.load(f)

for i in data_SRK_polyTdep:
    data_SRK_polyTdep = i
    
FIM_SRK_polyTdep = data_SRK_polyTdep['Total']

eigvals, eigvecs = np.linalg.eig(FIM_SRK_polyTdep)
print('Eigenvalues:',eigvals)
print('')
print('Eigenvectors:',eigvecs)
print('')
trace = np.trace(FIM_SRK_polyTdep)
print('Trace:',trace)
print('')
det = np.linalg.det(FIM_SRK_polyTdep)
print('Determinant:',det)
CN = eigvals.max()/eigvals.min()
print('CN:',CN)

Eigenvalues: [6.16761010e+16 4.33621956e+14 4.76429466e+13 3.28907184e+11
 3.96053052e+10 2.81086576e+08 1.43195787e+07 3.52238142e+04]

Eigenvectors: [[ 0.23936248 -0.2415815   0.46054146  0.2707524  -0.62235571  0.08471086
   0.45076036 -0.03537283]
 [-0.03351188  0.32975732  0.15992713 -0.57159844 -0.23347979 -0.61116713
   0.14352153 -0.29866218]
 [ 0.68330892 -0.1708741   0.43998533 -0.13325675  0.23814515 -0.11025572
  -0.47139799  0.03822322]
 [-0.07384326  0.66180691  0.36558324 -0.18075418 -0.11801478  0.45266065
  -0.08729222  0.40470548]
 [ 0.6494141   0.3175355  -0.42405654 -0.04897003  0.17096396  0.14154628
   0.49419518 -0.04144418]
 [-0.05393061  0.43485796  0.28033609  0.58547589  0.27282879 -0.07750642
  -0.02850193 -0.552598  ]
 [ 0.21058282  0.25341146 -0.41205417  0.29568476 -0.58709364 -0.17540669
  -0.50679191  0.04398758]
 [-0.01504458  0.10753853  0.08298061  0.34194936  0.19793129 -0.58773354
   0.21095354  0.65976136]]

Trace: 6.215773473019759e+16

Determina